services:
  - type: web
    name: finalproject-backend
    runtime: docker
    plan: free
    rootDir: Phase3 Project files/Laravel
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Smart Health Hub
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
  - type: web
    name: finalproject-chat
    runtime: node
    plan: free
    rootDir: Phase3 Project files/chat-node
    buildCommand: npm install
    startCommand: node index.js
